import Head from 'next/head'
import Link from 'next/link'
import { useEffect } from 'react'
import { useSelector } from 'react-redux'
import { router } from 'next/router'

export default function Index() {
  const userData = useSelector((state)=>state.user)
  useEffect(()=>{
    if(userData.loggedIn){
      router.replace('/home')
    }
  }, [userData.loggedIn])
  return (
    <>
      <Head>
        <title>Tic Tac Toe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-col items-center w-full h-full justify-center'>
        <header className='text-center w-full h-full flex justify-center flex-col py-4'>
          <h2 className='text-4xl'>
            async
          </h2>
          <h1 className='text-6xl'>
            tic tac
          </h1>
          <h1 className='text-6xl'>
            toe
          </h1>
        </header>
        <div className='w-full flex flex-col gap-4 p-4 font-semibold flex-shrink-0 text-lg'>
          <Link href={"/login"}>
            <button className='w-full py-2 bg-blue-500 rounded-lg hover:bg-blue-400'>
              Log In
            </button>
          </Link>
          <Link href={"/register"}>
            <button className='w-full py-2 bg-blue-800 rounded-lg hover:bg-blue-800'>
              Register
            </button>
          </Link>
        </div>
      </div>
    </>
  )
}
